name: pr

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  actions: read
  issues: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Info
      run: echo "Start..."
    - name: TEST
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} > token.txt && cat token.txt
