name: Preview Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
  jobs:
    build-site:
      runs-on: ubuntu-latest
      steps:
        - name: Preview Build
          run: |
            echo "preview build"
