name: Preview Start

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  preview-start:
    permissions:
      issues: write
      pull-requests: write
    name: start preview info
    runs-on: ubuntu-latest
    steps:
      - name: Update status comment
